version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - ./pg/initdb:/docker-entrypoint-initdb.d:ro
      - $RESTORE_DIR:/backup:ro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: unless-stopped
  odoo:
    image: odoo:15.0
    volumes:
      - ./openeducat_erp:/mnt/extra-addons:ro
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./odoo/restore-odoo-fs-if-empty.sh:/restore-odoo-fs-if-empty.sh:ro
      - $RESTORE_DIR:/backup:ro
    ports:
      - $ODOO_HTTP_PORT:8069
      - $ODOO_HTTP_LONGPOLL_PORT:8072
    depends_on:
      - db
